CREATE TABLE `poc_ds.demo` (

    SUB_OFFER_GST_PARTIC_KEY NUMERIC(19),

    EXTL_CAMPAIGN_KEY NUMERIC(19),

    SUB_OFFER_GST_PARTIC_STAT_CD STRING,

    CREAT_USR_ID STRING,

    CREAT_TS TIMESTAMP);
